Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*'
Style/ClassAndModuleChildren:
  Exclude:
    - 'spec/**/*'
Metrics/LineLength:
  Exclude:
    - 'spec/**/*'
Style/Documentation:
  Enabled: false
Style/FileName:
  Exclude:
    - 'bin/codeclimate-rubocop'
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%w': '[]'
    '%W': '[]'
Style/StringLiterals:
  Enabled: false
Style/TrailingComma:
  Enabled: false
Style/DotPosition:
  EnforcedStyle: 'trailing'
  Enabled: true
Style/MultilineOperationIndentation:
  Enabled: false
